# This workflow will build a new docker image and push it to the registry on a new push to main.
name: "CI: Build and Push Docker Image"

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-latest:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main' # Running this job only for master branch

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/caddy-cloudflare:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/caddy-cloudflare:latest
